"""
EXP-278b: DEEP AUDIT - MATH ERRORS + PHYSICS ISSUES
=====================================================
Hostile referee perspective. Check everything a reviewer would flag.
"""
import numpy as np

PHI = (1 + np.sqrt(5)) / 2
PHI_prime = (1 - np.sqrt(5)) / 2
a1 = 5; b1 = 6; N = 120; h = 30
N_eig = 9; N_gen = 3
m_e_MeV = 0.51099895
alpha_exp = 1/137.035999084

print("="*72)
print("EXP-278b: DEEP PAPER AUDIT (MATH + PHYSICS)")
print("="*72)

# ============================================================
# ERROR #1: Electron "unit" claim
# ============================================================
print("\n=== ERROR #1: Electron 'unit' claim ===")
print("Paper Table (Units and Primes):")
print("  'e, mu, tau, u, d, s ... various ... 1 ... Units (|N|=1)'")
print("  But electron has (a,b)=(0,0), so z_e = 0+0*phi = 0")
print(f"  N(0) = 0^2 + 0*0 - 0^2 = 0, NOT 1")
print()
print("  The paper claims 'Six of nine fermions are units'")
print("  But z=0 is the ZERO element, not a unit.")
print()
print("  POSSIBLE FIX: The electron is the ground state (n=0, z=phi^0=1).")
print("  If z_e = 1 = (1,0), then N(1) = 1. But this contradicts (a,b)=(0,0).")
print("  The issue: the mass formula uses (a,b)=(0,0) for n=0,")
print("  but the Z[phi] element phi^0 = 1 has (a,b)=(1,0), n=5.")
print("  VERDICT: The paper conflates two different z's. MUST BE FIXED.")

# ============================================================
# ERROR #2: Spectral gap multiplicity
# ============================================================
print("\n=== ERROR #2: Spectral gap multiplicity ===")
print("Paper line ~237: 'spectral gap lambda_min = 12-6*phi (multiplicity 1)'")
print("Adjacency eigenvalue table: lambda_1 = 6*phi has multiplicity 4")
print("Laplacian eigenvalue = 12 - lambda_A, same multiplicity")
print(f"  So 12-6*phi has multiplicity 4, NOT 1!")
print()
print("VERDICT: Mathematical error. Multiplicity is 4.")

# ============================================================
# ERROR #3: Cohn-Kumar 'in R^4'
# ============================================================
print("\n=== ERROR #3: Cohn-Kumar theorem statement ===")
print("Paper: '600-cell is unique universal energy minimizer in R^4")
print("        for all completely monotonic potentials'")
print("Actual theorem (Cohn-Kumar 2007): universal optimality of 120 points on S^3")
print("The statement 'in R^4' is incorrect - should be 'on S^3'.")
print("VERDICT: Imprecise statement, easily fixable.")

# ============================================================
# ERROR #4: Generation Theorem wording
# ============================================================
print("\n=== ERROR #4: Generation Theorem vs electron ===")
print("Paper: 'lepton exponents n_lep = {0, 11, 17}'")
print("  '(where the electron ground state n_e = 0 is subtracted")
print("   from the a = 1 line value n = 5)'")
print()
print("Generation Theorem selects b in {0,1,2} on a=1 line:")
print(f"  b=0: n = 5*1+6*0 = 5")
print(f"  b=1: n = 5*1+6*1 = 11")
print(f"  b=2: n = 5*1+6*2 = 17")
print("So the a=1 line gives {5, 11, 17}, NOT {0, 11, 17}.")
print()
print("The electron (n=0) has (a,b)=(0,0), which is NOT on a=1 line.")
print("The statement about 'subtracting' is confusing and incorrect.")
print("VERDICT: Misleading wording. Need to explain that electron")
print("is the reference point (phi^0=1), not generated by the theorem.")

# ============================================================
# WARNING #1: 96 = 16*3*2 and sterile neutrino
# ============================================================
print("\n=== WARNING #1: 96 = 16*3*2 ===")
print("Paper: '96 = 16 x (fermions per gen) x 3 (gens) x 2 (chiralities)'")
print("Standard Model has 15 Weyl fermions per generation (no nu_R):")
print("  q_L(6) + u_R(3) + d_R(3) + l_L(2) + e_R(1) = 15")
print("  16 = 15 + 1 (right-handed neutrino)")
print("This IMPLIES the framework predicts a sterile neutrino per generation.")
print("VERDICT: Should be explicitly stated as a PREDICTION, not assumed.")

# ============================================================
# WARNING #2: NCG vs simplicial Dirac operator
# ============================================================
print("\n=== WARNING #2: NCG vs simplicial D ===")
print("Paper cites Chamseddine-Connes spectral action [1997].")
print("Connes' framework uses spectral triple (A, H, D) with:")
print("  A = C^inf(M) tensor A_F (almost-commutative geometry)")
print("  D = D_M tensor 1 + gamma_5 tensor D_F")
print("  where A_F encodes the SM (algebra M_2(H) + M_4(C))")
print()
print("The paper uses D = d + d* on the simplicial complex.")
print("This is the COMBINATORIAL Dirac operator, NOT the NCG one.")
print("The connection between these two is NON-TRIVIAL.")
print("VERDICT: Major conceptual gap. Should clarify the distinction.")

# ============================================================
# WARNING #3: 'All dimensionless ratios are predicted'
# ============================================================
print("\n=== WARNING #3: 'All dimensionless ratios' claim ===")
print("The abstract says: 'All dimensionless ratios are predicted.'")
print("But:")
print("  - alpha(m_Z)/alpha(0) = 1.0628 is EXTERNAL INPUT")
print("  - m_W(exp) = 80.377 GeV used for Higgs (not derived m_W)")
print("  - Bare fermion masses have 3-21% errors")
print("  - Down quark: 21% error (corrected: 10%)")
print("  - Top quark: 20% error (corrected: 1.8%)")
print("VERDICT: 'All dimensionless ratios are predicted' is overstated.")
print("  Better: 'All dimensionless ratios have algebraic formulas'")

# ============================================================
# WARNING #4: CKM corrections - derived or fitted?
# ============================================================
print("\n=== WARNING #4: CKM correction coefficients ===")
print("Paper gives corrections to bare CKM angles:")
print("  theta_12: 1 - 2*alpha_s/(3*pi)  -- coeff 2/3")
print("  theta_23: 1 + 5*alpha_s/pi      -- coeff 5")
print("  theta_13: 1 + sin^2(tW)         -- coeff 6/26")
print()
print("These are IDENTIFIED with E8 leg ratios AFTER the fact.")
print("Question: can you derive WHICH correction goes with WHICH angle?")
print("Answer: paper says 'partially derived', but the corrections are")
print("presented as if derived. The FORMS (1 +/- X*coupling/pi) look")
print("like standard perturbative QCD/EW corrections, but the specific")
print("coefficients are pattern-matched, not first-principles derived.")
print("VERDICT: Honest (says 'partially derived') but could be clearer.")

# ============================================================
# WARNING #5: m_H/m_W = phi - 8*alpha
# ============================================================
print("\n=== WARNING #5: Higgs mass formula ===")
print("Paper: m_H/m_W = phi - 8*alpha, where 8 = rank(E8)")
print("  Bare: dihedral ratio = 1.552 (DERIVED, 0.99% error)")
print("  Correction: -8*alpha = -0.058 (PATTERN)")
print()
print("The coefficient 8 is 'identified' with rank(E8).")
print("But given phi ~ 1.618 and we need ratio ~ 1.560,")
print("the correction is phi - 1.560 = 0.058 ~ 8*alpha.")
print("Any integer n with n*alpha ~ 0.058 would work: n ~ 7.95")
print("So 8 is essentially the nearest integer to (phi-m_H/m_W)/alpha.")
print("It HAPPENS to be rank(E8), but this could be coincidental.")
print("VERDICT: Honest (paper says 'pattern'), but referee will be skeptical.")

# ============================================================
# WARNING #6: '40+ quantities at sub-percent'
# ============================================================
print("\n=== WARNING #6: Count of predictions ===")
print("Abstract: '40+ quantities predicted at the sub-percent level'")
print("Let me count sub-percent predictions:")
count = 0
predictions = [
    ("alpha", 0.0001, True),
    ("alpha_s", 0.11, True),
    ("sin^2(tW)", 0.19, True),
    ("m_Z", 0.09, True),
    ("m_H/m_W", 0.09, True),
    ("m_e/m_P", 0.24, True),
    ("theta_12 CKM", 0.001, True),
    ("theta_23 CKM", 0.17, True),
    ("theta_13 CKM", 0.096, True),
    ("sin2_13 PMNS", 0.16, True),
    ("sin2_12 PMNS", 0.26, True),
    ("sin2_23 PMNS", 0.32, True),
    ("delta_CKM", 0.77, True),
    ("delta_PMNS", 0.36, True),
    ("theta_QCD", 0, True),
    ("m_3 (neutrino)", 1.0, False),  # <1% but borderline
    ("J (Jarlskog)", 1.1, False),
    ("N_gen=3", 0, True),
    ("gamma_PPN=1", 0, True),
    ("Gauge group", 0, True),
    # Masses sub-percent: only u (0.2%) and tau (2.7% - NOT sub-percent)
    ("m_u bare", 0.2, True),
]
for name, err, sub_pct in predictions:
    if sub_pct:
        count += 1

print(f"  Sub-percent (strict): {count}")
print("  Getting to 40+ requires counting:")
print("  - 9 mass exponents (exact) = 9")
print("  - 4 sum rules (exact) = 4")
print("  - CKM exponent identities = 3")
print("  - 6 sector corrections = 6")
print("  - gap-Planck identities = 2")
print("  - hierarchy identity = 1")
print(f"  Total with algebraic identities: {count} + ~25 = {count+25}")
print("VERDICT: '40+' is defensible if you count exact algebraic")
print("  identities (sum rules, exponent relations, etc.).")
print("  But 'at sub-percent' is misleading for some.")

# ============================================================
# PHYSICS CHECK: Neutrino mass (fix unit bug)
# ============================================================
print("\n=== Neutrino Mass (corrected units) ===")
m3_MeV = 2 * m_e_MeV / PHI**35
m3_eV = m3_MeV * 1e6  # MeV to eV
m3_meV = m3_eV * 1e3   # eV to meV
print(f"  phi^35 = {PHI**35:.2f}")
print(f"  m_3 = 2 * {m_e_MeV} MeV / {PHI**35:.2f}")
print(f"       = {m3_MeV:.4e} MeV")
print(f"       = {m3_eV:.4f} eV")
print(f"       = {m3_meV:.2f} meV")
print(f"  Experimental: sqrt(Dm31^2) ~ 49.5 meV")
m3_error = abs(m3_meV - 49.53)/49.53 * 100
print(f"  Error: {m3_error:.2f}%")
print("  Paper claims: m_3 = 0.0495 eV (<1% error) -- CORRECT")

# ============================================================
# PHYSICS CHECK: Is Dm21/Dm31 = 4*alpha correct?
# ============================================================
print("\n=== Delta m^2 ratio check ===")
Dm21 = 7.53e-5  # eV^2
Dm31 = 2.453e-3  # eV^2
ratio_exp = Dm21/Dm31
pred = 4*alpha_exp
print(f"  Dm21/Dm31 (exp) = {ratio_exp:.5f}")
print(f"  4*alpha = {pred:.5f}")
print(f"  Error: {abs(ratio_exp-pred)/ratio_exp*100:.1f}%")
print("  Paper claims 1.24% error -- but actual is 4.9%!")
print("  POSSIBLE: different PDG values used. Let me check:")
# PDG 2024: Dm21^2 = 7.53e-5, Dm31^2 = 2.453e-3 (NO)
# Maybe Dm31^2 = 2.525e-3 (inverted hierarchy)?
Dm31_v2 = 2.525e-3
ratio_v2 = Dm21/Dm31_v2
err_v2 = abs(ratio_v2 - pred)/ratio_v2 * 100
print(f"  With Dm31^2 = 2.525e-3 (NH, older): ratio={ratio_v2:.5f}, err={err_v2:.1f}%")
# Try Dm21 = 7.42e-5 (older value)
Dm21_v3 = 7.42e-5
ratio_v3 = Dm21_v3/Dm31
err_v3 = abs(ratio_v3 - pred)/ratio_v3 * 100
print(f"  With Dm21^2 = 7.42e-5 (older): ratio={ratio_v3:.5f}, err={err_v3:.1f}%")
print("  VERDICT: The 1.24% claim needs updated PDG values")

# ============================================================
# PHYSICS CHECK: The Weinberg angle derivation
# ============================================================
print("\n=== Weinberg angle ===")
print("Paper claims TWO derivations:")
print("  (i) 6 decagonal vs 20 tetrahedral structures per vertex")
print("  (ii) b1/dim(phi-sector) = 6/26")
print()
print("For (ii): dim(phi-sector) = 4+9+9+4 = 26")
print(f"  sin^2(tW) = 6/26 = {6/26:.6f}")
print(f"  Experimental: 0.23121(4)")
print(f"  Error: {abs(6/26-0.23121)/0.23121*100:.2f}%")
print()
print("NOTE: The experimental value 0.23121 is at m_Z scale (MSbar).")
print("The framework claims this is the TREE-LEVEL value.")
print("Tree-level sin^2(tW) in the SM is 3/8 = 0.375 at GUT scale,")
print("running to ~0.231 at m_Z. The paper's value matches the LOW-energy")
print("value, suggesting it's predicting the renormalized value directly.")
print("VERDICT: This is OK but should be noted - the comparison is at m_Z scale.")

# ============================================================
# PHYSICS CHECK: alpha_s scale
# ============================================================
print("\n=== alpha_s scale ===")
print(f"  Framework: alpha_s = 1/(2*phi^3) = {1/(2*PHI**3):.6f}")
print(f"  PDG at m_Z: alpha_s(m_Z) = 0.1179 +/- 0.0009")
print(f"  Error: {abs(1/(2*PHI**3)-0.1179)/0.1179*100:.2f}%")
print()
print("The paper says this is alpha_s(M_Z) explicitly.")
print("alpha_s runs strongly: alpha_s(1 GeV) ~ 0.5, alpha_s(m_Z) ~ 0.118")
print("The framework gives a FIXED value matching m_Z scale.")
print("VERDICT: OK if interpreted as prediction at m_Z. But paper doesn't")
print("explain WHY the framework gives the m_Z value specifically.")

# ============================================================
# PHYSICS CHECK: Spectral action coefficients
# ============================================================
print("\n=== Spectral action coefficients ===")
print("Paper claims c_k are from Seeley-DeWitt expansion.")
print("But on a FINITE complex (2640 eigenstates), the Seeley-DeWitt")
print("expansion is an APPROXIMATION, not exact.")
print()
print("For a finite Dirac operator, the spectral action is:")
print("  S = sum_i f(lambda_i/Lambda)")
print("and the 'Seeley-DeWitt' coefficients are just moments:")
print("  c_0 = Tr(1) = dim(H) = 2640  (EXACT)")
print("  c_1 = Tr(D^2) = sum lambda_i^2 = 14880 (EXACT)")
print("  c_2 = Tr(D^4)/2 = sum lambda_i^4 / 2 = 55920 (EXACT)")
print()
print("These are exact because the spectrum is finite.")
print("VERDICT: The labeling 'Seeley-DeWitt' is slightly misleading")
print("(that expansion is for continuous manifolds), but the")
print("coefficients themselves are well-defined and exact.")

# ============================================================
# DEEPER: Is 14880 really Tr(D^2)?
# ============================================================
print("\n=== Verifying c_1 = Tr(D^2) = 14880 ===")
print("D = d + d*. D^2 = dd* + d*d = direct sum of Hodge Laplacians.")
print("Tr(D^2) = sum Tr(Delta_p) for p=0,1,2,3.")
print()
print("Per-simplex traces: {12, 7, 5, 4}")
print("  Tr(Delta_0) = 120 * 12 = 1440")
print("  Tr(Delta_1) = 720 * 7 = 5040")
print("  Tr(Delta_2) = 1200 * 5 = 6000")
print("  Tr(Delta_3) = 600 * 4 = 2400")
print(f"  Total: {1440+5040+6000+2400} = 14880")
print()
print("But wait: per-simplex trace means diagonal average, not Tr/dim.")
print("Delta_0 has Tr = sum of vertex degrees = 120*12 = 1440 (since regular graph).")
print("Delta_1 has Tr = ? This is the edge Hodge Laplacian = B+C.")
print("  B = d_0*d_0^T, C = d_1^T*d_1")
print("  Tr(B): each edge contributes the sum of degrees of its endpoints - 2")
print("    = 2*(12-1) = 22 per edge? No...")
print("  Actually Tr(B) = Tr(d_0*d_0^T) = ||d_0||_F^2 = Tr(d_0^T*d_0) = Tr(Delta_0)")
print("  So Tr(B) = Tr(Delta_0) = 1440")
print("  Tr(C): diagonal of C = d_1^T*d_1")
print("  C_ee = number of triangles containing edge e = 5 (since Tr(C)/E = 3600/720 = 5)")
print("  So Tr(C) = 720*5 = 3600")
print("  Tr(Delta_1) = Tr(B) + Tr(C) = 1440 + 3600 = 5040")
print(f"  CHECK: 5040/720 = {5040/720} (should be 7)")
print()
print("Similarly:")
print("  Tr(Delta_2): each face has degree = edges in face + adjacent faces")
print("  = 3 + (number of face neighbors) = 3 + ?")
print("  If Tr(Delta_2)/1200 = 5, then Tr(Delta_2) = 6000")
print("  Tr(Delta_3): each tetrahedron has 4 faces")
print("  Tr(Delta_3) = 600 * 4 = 2400")
print("  CHECK: per-tetra trace = 4 = number of faces per cell")
print()
print("VERDICT: The per-simplex traces {12,7,5,4} are PLAUSIBLE but")
print("should be verified computationally (paper says they are).")
print("The sum 14880 is consistent IF these values are correct.")

# ============================================================
# CRITICAL: Is the hierarchy formula m_e/m_P = alpha^(4*phi^2) unique?
# ============================================================
print("\n=== Hierarchy formula uniqueness ===")
print("Claim: z_Planck = 4*phi^2 is UNIQUE with Tr=12, N=16.")
print("Quadratic: t^2 - 12t + 16 = 0, roots = 6 +/- 2*sqrt(5)")
z1 = 6 + 2*np.sqrt(5)
z2 = 6 - 2*np.sqrt(5)
print(f"  z1 = {z1:.6f} = 4*phi^2 = {4*PHI**2:.6f}")
print(f"  z2 = {z2:.6f} = 4*phi'^2 = {4*PHI_prime**2:.6f}")
print(f"  Both roots are POSITIVE (z2 = {z2:.4f} > 0)")
print()
print("  Wait -- z2 > 0! The paper says z is unique with z>0 and z'>0.")
print(f"  z1 = 4*phi^2 = {z1:.4f}, z1' (Galois conj) = z2 = {z2:.4f}")
print(f"  z2 = 4*phi'^2 = {z2:.4f}, z2' (Galois conj) = z1 = {z1:.4f}")
print()
print("  Both roots have z>0 AND z'>0 (since z2 = z1' > 0).")
print("  BUT z1 and z2 are Galois conjugates of EACH OTHER.")
print("  So there is only ONE element up to Galois conjugation.")
print("  The CONVENTION z > z' selects z1 = 4*phi^2.")
print("  VERDICT: Unique up to Galois conjugation. Paper is correct")
print("  but should clarify the uniqueness is modulo Galois action.")

# For alpha_s:
print("\n  For alpha_s: z^2 - 8z - 4 = 0")
z1_s = 4 + 2*np.sqrt(5)
z2_s = 4 - 2*np.sqrt(5)
print(f"  z1 = {z1_s:.4f}, z2 = {z2_s:.4f}")
print(f"  z2 < 0, so UNIQUELY z1 is the positive root.")
print("  Paper correctly notes 'The other root 6-4*phi < 0'")
# Wait, paper says roots of z^2-8z-4=0 are 4+/-2*sqrt(5)
# z=4+2*sqrt(5)=4+2*2.236=8.472
# z=4-2*sqrt(5)=4-4.472=-0.472
# Paper says "other root 6-4*phi < 0"
# 6-4*phi = 6-6.472 = -0.472. But the root is 4-2*sqrt(5) = -0.472.
# 6-4*phi = 6-4*1.618 = -0.472. And 4-2*sqrt(5) = 4-4.472 = -0.472.
# These are equal: 4-2*sqrt(5) = 4-2*(2*phi-1) = 6-4*phi. CHECK.
check_val = abs((4-2*np.sqrt(5)) - (6-4*PHI))
print(f"  Verify: 4-2*sqrt(5) = 6-4*phi? Diff = {check_val:.2e} (YES)")

# ============================================================
# QUESTIONABLE: Delta m^2 ratio claim
# ============================================================
print("\n=== Dm^2 ratio check ===")
print("Paper (Section 13 Predictions): 'Delta m^2_21 / Delta m^2_31 = 4*alpha'")
print("  with '1.24% error'")
# PDG 2024 best-fit values:
# Dm21^2 = (7.53 +/- 0.18) x 10^-5 eV^2
# Dm31^2 = (2.453 +/- 0.033) x 10^-3 eV^2 (NH)
ratio = 7.53e-5 / 2.453e-3
four_alpha = 4/137.036
print(f"  PDG 2024: ratio = {ratio:.6f}")
print(f"  4*alpha = {four_alpha:.6f}")
print(f"  Error: {abs(ratio-four_alpha)/ratio*100:.2f}%")
# Try NuFIT 5.2 (2022) values: Dm21 = 7.42, Dm31 = 2.515
ratio2 = 7.42e-5 / 2.515e-3
print(f"  NuFIT 5.2: ratio = {ratio2:.6f}, err = {abs(ratio2-four_alpha)/ratio2*100:.2f}%")
# To get 1.24% error: need ratio ~ 0.02955
needed = four_alpha * (1 + 0.0124)
print(f"  For 1.24% error: need ratio = {needed:.6f}")
print(f"  This would require Dm21/Dm31 = {needed:.6f}")
print(f"  = Dm21/(Dm21/{needed:.6f}) => Dm31 = Dm21/{needed:.6f}")
print(f"  With Dm21 = 7.53e-5: Dm31 = {7.53e-5/needed:.4e}")
print("  VERDICT: 1.24% error may use older experimental values.")
print("  With PDG 2024: error is ~5%. Should update or remove.")

# ============================================================
# STRUCTURAL: The equation a1! = 4*a1*(a1+1)
# ============================================================
print("\n=== Diophantine equation origin ===")
print("Claim: 'the right side is four times the product of the")
print("  first two intersection numbers'")
print()
print("For 600-cell distance-regular graph with diameter d=5:")
print("  Intersection array: {12, 11, 10, 9, 8; 1, 2, 3, 4, 5}")
print("  So b_0=12, b_1=11, b_2=10, b_3=9, b_4=8")
print("  And c_1=1, c_2=2, c_3=3, c_4=4, c_5=5")
print("  With a_i = 12 - b_i - c_i:")
print("  a_0=0, a_1=0, a_2=0, a_3=0, a_4=0 (since b_i+c_i=12 for i>0)")
print()
print("  'First two intersection numbers' = a_1 and c_1?")
print("  a_1 = 0 and c_1 = 1: product = 0. WRONG.")
print("  Or b_0 and c_1? 12*1 = 12. 4*12 = 48. WRONG.")
print("  Or the PAPER's a_1 = 5 (graph diameter) and a_1+1 = 6?")
print("  These are NOT standard intersection numbers!")
print()
print("  Actually, the 600-cell has a_1(paper) = graph diameter = 5.")
print("  Standard notation: a_1 (paper) != a_1 (intersection number).")
print("  The intersection numbers of the 600-cell are c_i, a_i, b_i")
print("  where c_i = i, b_i = 12-i, a_i = 0 for the standard scheme.")
print()
print("  VERDICT: The 'geometric origin' claim about intersection numbers")
print("  is UNCLEAR. The paper uses a_1 for graph diameter, not the")
print("  standard intersection number. Should be clarified.")

# ============================================================
# SUMMARY
# ============================================================
print("\n" + "="*72)
print("DEEP AUDIT SUMMARY")
print("="*72)
print()
print("MATHEMATICAL ERRORS (must fix):")
print("  1. Electron |N|=0, not 1 (not a unit). Paper claims 'six of nine are units'.")
print("  2. Spectral gap multiplicity = 4, paper says 1.")
print("  3. Cohn-Kumar: 'on S^3' not 'in R^4'.")
print("  4. Generation Theorem: electron not on a=1 line; wording misleading.")
print()
print("PHYSICS ISSUES (should address):")
print("  5. 96=16*3*2 implies sterile neutrino -- should state explicitly.")
print("  6. NCG Dirac operator != simplicial D -- conceptual gap.")
print("  7. 'All dimensionless ratios predicted' is overstated.")
print("  8. CKM correction coefficients pattern-matched, not derived.")
print("  9. m_H correction coeff 8 could be coincidental.")
print(" 10. Dm^2_21/Dm^2_31 = 4*alpha: 1.24% error uses old data, now ~5%.")
print(" 11. Diophantine 'intersection numbers' claim needs clarification.")
print(" 12. alpha_s and sin^2(tW) compared at m_Z scale without RG justification.")
print()
print("COSMETIC:")
print(" 13. '40+ quantities at sub-percent' -- defensible but generous.")
print(" 14. Seeley-DeWitt labeling on finite complex -- slightly misleading.")
print(" 15. Planck z 'uniqueness' should note 'up to Galois conjugation'.")
print()
print("OVERALL ASSESSMENT:")
print("  Paper is mathematically sophisticated with impressive numerical matches.")
print("  Errors 1-4 are fixable. Issues 5-12 are the ones a tough referee")
print("  would push back on hardest. The core results (alpha, alpha_s, sin^2(tW),")
print("  mass exponents, CKM angles, CP violation) are numerically compelling.")
print("  The main theoretical weakness is the gap between 'pattern' and 'derivation'")
print("  for several key results (CKM corrections, m_H, PMNS angles).")

print("\n" + "="*72)
print("EXP-278b COMPLETE")
print("="*72)
