#!/usr/bin/env python3
"""Run the explicit verifier registry for the focused 600-cell Regge lab."""

import os
import subprocess
import sys
import time


HERE = os.path.dirname(os.path.abspath(__file__))
os.chdir(HERE)

scripts = [
    "verify_documentation_layout.py",
    "verify_gravity_600cell_barycentric_product_slab.py",
    "verify_gravity_600cell_canonical_data_admissibility.py",
    "verify_gravity_600cell_canonical_data_carrier.py",
    "verify_gravity_600cell_canonical_data_projection.py",
    "verify_gravity_600cell_canonical_data_space_identification.py",
    "verify_gravity_600cell_cellular_frustum_anisotropic_rigidity.py",
    "verify_gravity_600cell_cellular_frustum_anisotropic_rigidity_adversarial.py",
    "verify_gravity_600cell_cellular_frustum_relative_poincare.py",
    "verify_gravity_600cell_cellular_frustum_relative_poincare_adversarial.py",
    "verify_gravity_600cell_cellular_frustum_relative_poincare_covariance_correction.py",
    "verify_gravity_600cell_cellular_weak_lapse_all_n.py",
    "verify_gravity_600cell_cellular_weak_lapse_blind.py",
    "verify_gravity_600cell_cellular_weak_lapse_comparison.py",
    "verify_gravity_600cell_chromatic_chamber_selector.py",
    "verify_gravity_600cell_chromatic_cover_orbits.py",
    "verify_gravity_600cell_chromatic_degree_selector.py",
    "verify_gravity_600cell_corrected_strut_alignment.py",
    "verify_gravity_600cell_corrected_strut_alignment_adversarial.py",
    "verify_gravity_600cell_corrected_strut_canonical_intersection.py",
    "verify_gravity_600cell_corrected_strut_canonical_intersection_adversarial.py",
    "verify_gravity_600cell_corrected_strut_carrier.py",
    "verify_gravity_600cell_dust_action_reduced_scalar.py",
    "verify_gravity_600cell_dust_action_solver_repair.py",
    "verify_gravity_600cell_dust_action_solver_repair_continuation.py",
    "verify_gravity_600cell_dust_action_solver_repair_continuation_result.py",
    "verify_gravity_600cell_dust_action_york_direct_precision.py",
    "verify_gravity_600cell_dust_action_york_direct_precision_adversarial.py",
    "verify_gravity_600cell_dust_action_york_negative.py",
    "verify_gravity_600cell_dust_action_york_scale_invariant_adversarial.py",
    "verify_gravity_600cell_dust_anchored_counterterm.py",
    "verify_gravity_600cell_dust_boundary_coboundary.py",
    "verify_gravity_600cell_dust_canonical_continuation.py",
    "verify_gravity_600cell_dust_canonical_legendre_rank.py",
    "verify_gravity_600cell_dust_centered_jacobi.py",
    "verify_gravity_600cell_dust_conformal_shape_dynamics.py",
    "verify_gravity_600cell_dust_conformal_supermetric.py",
    "verify_gravity_600cell_dust_curvature_kernel_transport.py",
    "verify_gravity_600cell_dust_dynamic_tangent.py",
    "verify_gravity_600cell_dust_dynamic_tangent_conjugacy.py",
    "verify_gravity_600cell_dust_dynamic_tangent_conjugacy_enumeration.py",
    "verify_gravity_600cell_dust_dynamic_tangent_precision.py",
    "verify_gravity_600cell_dust_exact_lapse_path.py",
    "verify_gravity_600cell_dust_fourth_tick.py",
    "verify_gravity_600cell_dust_full_anisotropic_legendre_rank.py",
    "verify_gravity_600cell_dust_full_boundary_tangent.py",
    "verify_gravity_600cell_dust_full_lapse_schur.py",
    "verify_gravity_600cell_dust_gauge_quotient.py",
    "verify_gravity_600cell_dust_gauge_quotient_precision.py",
    "verify_gravity_600cell_dust_generalized_bundle_direct_precision.py",
    "verify_gravity_600cell_dust_generalized_bundle_residual.py",
    "verify_gravity_600cell_dust_generalized_mode_closure.py",
    "verify_gravity_600cell_dust_generalized_phase_transport.py",
    "verify_gravity_600cell_dust_generalized_phase_transport_adversarial.py",
    "verify_gravity_600cell_dust_generalized_transported_intersection.py",
    "verify_gravity_600cell_dust_generalized_transported_intersection_adversarial.py",
    "verify_gravity_600cell_dust_homogeneous_curvature_kernel.py",
    "verify_gravity_600cell_dust_homogeneous_two_by_two.py",
    "verify_gravity_600cell_dust_homothetic_canonical_lapse.py",
    "verify_gravity_600cell_dust_homothetic_forward_root.py",
    "verify_gravity_600cell_dust_homothetic_mass_conservation.py",
    "verify_gravity_600cell_dust_hyperbolic_lapse_alignment.py",
    "verify_gravity_600cell_dust_implicit_jacobian.py",
    "verify_gravity_600cell_dust_internal_curvature_response.py",
    "verify_gravity_600cell_dust_lapse_schur.py",
    "verify_gravity_600cell_dust_lapse_stiffness_origin.py",
    "verify_gravity_600cell_dust_later_slab_tangent.py",
    "verify_gravity_600cell_dust_mass_response.py",
    "verify_gravity_600cell_dust_mass_response_adversarial.py",
    "verify_gravity_600cell_dust_negative_fiber_transport.py",
    "verify_gravity_600cell_dust_negative_intersection_roundoff_resolution.py",
    "verify_gravity_600cell_dust_negative_shape_dynamics.py",
    "verify_gravity_600cell_dust_negative_shape_kinetic_metric.py",
    "verify_gravity_600cell_dust_negative_shape_root_count.py",
    "verify_gravity_600cell_dust_negative_transported_intersection.py",
    "verify_gravity_600cell_dust_negative_transported_intersection_adversarial.py",
    "verify_gravity_600cell_dust_nonlinear_boundary_covariance.py",
    "verify_gravity_600cell_dust_nonlinear_boundary_covariance_seeds.py",
    "verify_gravity_600cell_dust_nonlinear_defect.py",
    "verify_gravity_600cell_dust_nonlinear_relative.py",
    "verify_gravity_600cell_dust_pseudolongitudinal_shifted.py",
    "verify_gravity_600cell_dust_pseudolongitudinal_shifted_adversarial.py",
    "verify_gravity_600cell_dust_pseudolongitudinal_shifted_rank_correction.py",
    "verify_gravity_600cell_dust_regular_lapse_identity.py",
    "verify_gravity_600cell_dust_rigidity_york.py",
    "verify_gravity_600cell_dust_second_homothetic_tick.py",
    "verify_gravity_600cell_dust_second_tick_homotopy.py",
    "verify_gravity_600cell_dust_second_tick_local_correction.py",
    "verify_gravity_600cell_dust_second_tick_stationary_target.py",
    "verify_gravity_600cell_dust_shape_stiffness.py",
    "verify_gravity_600cell_dust_shifted_centered.py",
    "verify_gravity_600cell_dust_shifted_conformal_shape.py",
    "verify_gravity_600cell_dust_shifted_direct_precision.py",
    "verify_gravity_600cell_dust_shifted_jacobi.py",
    "verify_gravity_600cell_dust_shifted_negative_persistence.py",
    "verify_gravity_600cell_dust_shifted_precision_audit.py",
    "verify_gravity_600cell_dust_shifted_shape_stiffness.py",
    "verify_gravity_600cell_dust_stagnation.py",
    "verify_gravity_600cell_dust_stationary_base.py",
    "verify_gravity_600cell_dust_stationary_momentum_envelope.py",
    "verify_gravity_600cell_dust_stationary_root_enumeration.py",
    "verify_gravity_600cell_dust_third_tick_local_correction.py",
    "verify_gravity_600cell_dust_third_tick_stationary_roots.py",
    "verify_gravity_600cell_dust_third_tick_stationary_target.py",
    "verify_gravity_600cell_dust_three_slice_jacobi.py",
    "verify_gravity_600cell_dust_two_slab_gluing.py",
    "verify_gravity_600cell_dust_two_step_full_tangent.py",
    "verify_gravity_600cell_dust_weak_lapse_recurrence.py",
    "verify_gravity_600cell_dust_weak_scale_path.py",
    "verify_gravity_600cell_finite_height_asymptotic_map.py",
    "verify_gravity_600cell_finite_height_asymptotic_map_adversarial.py",
    "verify_gravity_600cell_finite_height_census.py",
    "verify_gravity_600cell_finite_height_classification.py",
    "verify_gravity_600cell_finite_height_classification_adversarial.py",
    "verify_gravity_600cell_finite_height_composition.py",
    "verify_gravity_600cell_finite_height_composition_adversarial.py",
    "verify_gravity_600cell_finite_height_fourth_slab.py",
    "verify_gravity_600cell_finite_height_fourth_slab_adversarial.py",
    "verify_gravity_600cell_finite_height_invariant_region.py",
    "verify_gravity_600cell_finite_height_invariant_region_adversarial.py",
    "verify_gravity_600cell_finite_height_selector_audit.py",
    "verify_gravity_600cell_finite_height_selector_audit_adversarial.py",
    "verify_gravity_600cell_finite_height_third_slab.py",
    "verify_gravity_600cell_finite_height_third_slab_adversarial.py",
    "verify_gravity_600cell_full_equation_carrier_no_go.py",
    "verify_gravity_600cell_full_scale_strut_canonical_intersection.py",
    "verify_gravity_600cell_full_scale_strut_canonical_precision.py",
    "verify_gravity_600cell_full_scale_strut_canonical_precision_adversarial.py",
    "verify_gravity_600cell_full_scale_strut_carrier.py",
    "verify_gravity_600cell_full_scale_strut_homogeneous_resolution.py",
    "verify_gravity_600cell_full_scale_strut_homogeneous_resolution_adversarial.py",
    "verify_gravity_600cell_full_scale_strut_precision.py",
    "verify_gravity_600cell_full_scale_strut_symbolic_adversarial.py",
    "verify_gravity_600cell_full_scale_strut_symbolic_gap_resolution.py",
    "verify_gravity_600cell_generic_velocity_composition.py",
    "verify_gravity_600cell_generic_velocity_composition_adversarial.py",
    "verify_gravity_600cell_generic_velocity_cubic.py",
    "verify_gravity_600cell_generic_velocity_cubic_adversarial.py",
    "verify_gravity_600cell_generic_velocity_next_order.py",
    "verify_gravity_600cell_generic_velocity_next_order_adversarial.py",
    "verify_gravity_600cell_global_flex_holonomy.py",
    "verify_gravity_600cell_global_flex_holonomy_adversarial.py",
    "verify_gravity_600cell_global_variable_face_closure.py",
    "verify_gravity_600cell_homogeneous_pole_transversality.py",
    "verify_gravity_600cell_homothetic_frustum_action.py",
    "verify_gravity_600cell_homothetic_frustum_equivalence.py",
    "verify_gravity_600cell_local_data_lift.py",
    "verify_gravity_600cell_orbit_action_incidence.py",
    "verify_gravity_600cell_overlay_additive_transfer.py",
    "verify_gravity_600cell_overlay_face_poset.py",
    "verify_gravity_600cell_overlay_metric_compatibility.py",
    "verify_gravity_600cell_prism_shift_action.py",
    "verify_gravity_600cell_prism_shift_action_adversarial.py",
    "verify_gravity_600cell_prism_shift_canonical_elimination.py",
    "verify_gravity_600cell_prism_shift_canonical_elimination_adversarial.py",
    "verify_gravity_600cell_prism_shift_dynamic_extension.py",
    "verify_gravity_600cell_prism_shift_gluing.py",
    "verify_gravity_600cell_prism_shift_gluing_adversarial.py",
    "verify_gravity_600cell_projected_rank_edgewise_acceleration_adversarial.py",
    "verify_gravity_600cell_projected_rank_edgewise_acceleration_blind.py",
    "verify_gravity_600cell_projected_rank_edgewise_acceleration_comparison.py",
    "verify_gravity_600cell_projected_rank_edgewise_balanced_slab.py",
    "verify_gravity_600cell_projected_rank_edgewise_balanced_slab_adversarial.py",
    "verify_gravity_600cell_projected_rank_edgewise_carrier.py",
    "verify_gravity_600cell_projected_rank_edgewise_carrier_adversarial.py",
    "verify_gravity_600cell_projected_rank_edgewise_local_dust.py",
    "verify_gravity_600cell_projected_rank_edgewise_local_dust_adversarial.py",
    "verify_gravity_600cell_projected_refinement_acceleration_blind.py",
    "verify_gravity_600cell_projected_refinement_acceleration_comparison.py",
    "verify_gravity_600cell_published_dust_control.py",
    "verify_gravity_600cell_rational_data_lift.py",
    "verify_gravity_600cell_refined_boundary_cotangent.py",
    "verify_gravity_600cell_refined_boundary_cotangent_adversarial.py",
    "verify_gravity_600cell_refined_canonical_map_feasibility.py",
    "verify_gravity_600cell_refined_effective_h4_hessian.py",
    "verify_gravity_600cell_refined_h4_constrained_combined_envelope.py",
    "verify_gravity_600cell_refined_h4_constrained_directional_diagnostic.py",
    "verify_gravity_600cell_refined_h4_constrained_response.py",
    "verify_gravity_600cell_refined_h4_constrained_response_adversarial.py",
    "verify_gravity_600cell_refined_h4_constrained_response_auxiliary_diagnostic.py",
    "verify_gravity_600cell_refined_h4_constrained_response_corrected_adjudication.py",
    "verify_gravity_600cell_refined_h4_internal_jacobian.py",
    "verify_gravity_600cell_refined_h4_nested_reduction.py",
    "verify_gravity_600cell_refined_h4_null_coupling.py",
    "verify_gravity_600cell_refined_h4_null_coupling_adversarial.py",
    "verify_gravity_600cell_refined_h4_stationary_fill.py",
    "verify_gravity_600cell_refined_h4_stationary_root.py",
    "verify_gravity_600cell_refined_homogeneous_cotangent_lift.py",
    "verify_gravity_600cell_refined_homogeneous_cotangent_lift_adversarial.py",
    "verify_gravity_600cell_refined_local_curvature_mass.py",
    "verify_gravity_600cell_refined_local_curvature_mass_adversarial.py",
    "verify_gravity_600cell_refined_nonhomogeneous_coxeter_blocks.py",
    "verify_gravity_600cell_refined_nonhomogeneous_coxeter_blocks_adversarial.py",
    "verify_gravity_600cell_refined_nonhomogeneous_coxeter_census.py",
    "verify_gravity_600cell_refined_nonhomogeneous_coxeter_census_adversarial.py",
    "verify_gravity_600cell_refined_nonhomogeneous_internal_hessian.py",
    "verify_gravity_600cell_refined_nonhomogeneous_internal_hessian_diagnostic.py",
    "verify_gravity_600cell_relational_step_composition.py",
    "verify_gravity_600cell_relational_step_composition_adversarial.py",
    "verify_gravity_600cell_staircase_orientation_selector.py",
    "verify_gravity_600cell_static_gradient_prism_shift_reconciliation.py",
    "verify_gravity_600cell_static_vertex_gradient.py",
    "verify_gravity_600cell_static_vertex_gradient_adversarial.py",
    "verify_gravity_600cell_tetrahedral_prism_rigidity.py",
    "verify_gravity_600cell_tetrahedral_prism_rigidity_adversarial.py",
    "verify_gravity_600cell_tick_scale_covariance.py",
    "verify_gravity_600cell_tick_scale_covariance_adversarial.py",
    "verify_gravity_600cell_tick_scale_covariance_precision.py",
    "verify_gravity_600cell_tick_scale_covariance_state_correction.py",
    "verify_gravity_600cell_two_frustum_face_gluing.py",
    "verify_gravity_600cell_two_frustum_face_gluing_adversarial.py",
    "verify_gravity_600cell_universal_staircase_overlay.py",
    "verify_gravity_600cell_variable_face_connection.py",
    "verify_gravity_600cell_variable_face_connection_adversarial.py",
    "verify_gravity_box4_full_hessian.py",
    "verify_gravity_global_boundary_legendre.py",
    "verify_gravity_global_regge_orbits.py",
    "verify_gravity_global_regge_roots.py",
    "verify_gravity_global_tent_schedule.py",
    "verify_gravity_hamiltonian_constraint_gap.py",
    "verify_gravity_lorentzian_asymmetric_tent.py",
    "verify_gravity_lorentzian_tent.py",
    "verify_gravity_lorentzian_tent_legendre.py",
    "verify_gravity_lorentzian_tent_regular_evolution.py",
    "verify_gravity_lorentzian_volume_selection.py",
    "verify_gravity_metric_phase_space_canonicity.py",
    "verify_gravity_tent_move_regge.py",
    "verify_gravity_time_slab_canonicity.py",
]

# Deliberate exclusions must name an on-disk verifier and give a real reason.
DELIBERATELY_SKIPPED: dict[str, str] = {}

on_disk = {
    name for name in os.listdir(".")
    if name.startswith("verify_") and name.endswith(".py")
}
registered = set(scripts)
skipped = set(DELIBERATELY_SKIPPED)
duplicates = sorted({name for name in scripts if scripts.count(name) > 1})
unregistered = sorted(on_disk - registered - skipped)
missing_file = sorted(registered - on_disk)
missing_skip = sorted(skipped - on_disk)
overlap = sorted(registered & skipped)
empty_reason = sorted(
    name for name, reason in DELIBERATELY_SKIPPED.items()
    if not isinstance(reason, str) or not reason.strip()
)

if (
    unregistered
    or missing_file
    or missing_skip
    or overlap
    or duplicates
    or empty_reason
):
    print("=" * 70)
    print("COVERAGE ERROR -- the suite registry is inconsistent")
    print("=" * 70)
    for name in unregistered:
        print(f"  on disk but NOT registered : {name}")
    for name in missing_file:
        print(f"  registered but MISSING     : {name}")
    for name in missing_skip:
        print(f"  excluded but MISSING       : {name}")
    for name in overlap:
        print(f"  registered AND excluded    : {name}")
    for name in duplicates:
        print(f"  registered more than once  : {name}")
    for name in empty_reason:
        print(f"  exclusion lacks a reason   : {name}")
    sys.exit(2)

DEFAULT_TIMEOUT = 300
SCRIPT_TIMEOUTS = {
    "verify_gravity_600cell_canonical_data_admissibility.py": 3600,
    "verify_gravity_600cell_canonical_data_carrier.py": 3600,
    "verify_gravity_600cell_canonical_data_projection.py": 3600,
    "verify_gravity_600cell_canonical_data_space_identification.py": 3600,
    "verify_gravity_600cell_cellular_frustum_anisotropic_rigidity.py": 300,
    "verify_gravity_600cell_cellular_frustum_anisotropic_rigidity_adversarial.py": 300,
    "verify_gravity_600cell_cellular_frustum_relative_poincare.py": 300,
    "verify_gravity_600cell_cellular_frustum_relative_poincare_adversarial.py": 300,
    "verify_gravity_600cell_cellular_frustum_relative_poincare_covariance_correction.py": 300,
    "verify_gravity_600cell_cellular_weak_lapse_all_n.py": 3600,
    "verify_gravity_600cell_cellular_weak_lapse_blind.py": 3600,
    "verify_gravity_600cell_cellular_weak_lapse_comparison.py": 3600,
    "verify_gravity_600cell_corrected_strut_alignment.py": 1800,
    "verify_gravity_600cell_corrected_strut_alignment_adversarial.py": 1800,
    "verify_gravity_600cell_corrected_strut_canonical_intersection.py": 1800,
    "verify_gravity_600cell_corrected_strut_canonical_intersection_adversarial.py": 1800,
    "verify_gravity_600cell_dust_action_reduced_scalar.py": 28800,
    "verify_gravity_600cell_dust_action_solver_repair.py": 57600,
    "verify_gravity_600cell_dust_action_solver_repair_continuation.py": 57600,
    "verify_gravity_600cell_dust_action_solver_repair_continuation_result.py": 60,
    "verify_gravity_600cell_dust_action_york_direct_precision.py": 14400,
    "verify_gravity_600cell_dust_action_york_direct_precision_adversarial.py": 3600,
    "verify_gravity_600cell_dust_action_york_scale_invariant_adversarial.py": 3600,
    "verify_gravity_600cell_dust_canonical_continuation.py": 28800,
    "verify_gravity_600cell_dust_canonical_legendre_rank.py": 28800,
    "verify_gravity_600cell_dust_centered_jacobi.py": 3600,
    "verify_gravity_600cell_dust_conformal_shape_dynamics.py": 3600,
    "verify_gravity_600cell_dust_conformal_supermetric.py": 3600,
    "verify_gravity_600cell_dust_curvature_kernel_transport.py": 3600,
    "verify_gravity_600cell_dust_dynamic_tangent.py": 14400,
    "verify_gravity_600cell_dust_dynamic_tangent_conjugacy.py": 1800,
    "verify_gravity_600cell_dust_dynamic_tangent_conjugacy_enumeration.py": 1800,
    "verify_gravity_600cell_dust_dynamic_tangent_precision.py": 3600,
    "verify_gravity_600cell_dust_exact_lapse_path.py": 2400,
    "verify_gravity_600cell_dust_fourth_tick.py": 3600,
    "verify_gravity_600cell_dust_full_anisotropic_legendre_rank.py": 28800,
    "verify_gravity_600cell_dust_full_boundary_tangent.py": 28800,
    "verify_gravity_600cell_dust_full_lapse_schur.py": 28800,
    "verify_gravity_600cell_dust_gauge_quotient.py": 3000,
    "verify_gravity_600cell_dust_gauge_quotient_precision.py": 3000,
    "verify_gravity_600cell_dust_generalized_bundle_direct_precision.py": 10800,
    "verify_gravity_600cell_dust_generalized_bundle_residual.py": 14400,
    "verify_gravity_600cell_dust_generalized_mode_closure.py": 600,
    "verify_gravity_600cell_dust_generalized_phase_transport.py": 18000,
    "verify_gravity_600cell_dust_generalized_phase_transport_adversarial.py": 18000,
    "verify_gravity_600cell_dust_generalized_transported_intersection.py": 18000,
    "verify_gravity_600cell_dust_generalized_transported_intersection_adversarial.py": 18000,
    "verify_gravity_600cell_dust_homogeneous_curvature_kernel.py": 3600,
    "verify_gravity_600cell_dust_homogeneous_two_by_two.py": 3600,
    "verify_gravity_600cell_dust_homothetic_canonical_lapse.py": 3600,
    "verify_gravity_600cell_dust_homothetic_forward_root.py": 3600,
    "verify_gravity_600cell_dust_homothetic_mass_conservation.py": 3600,
    "verify_gravity_600cell_dust_hyperbolic_lapse_alignment.py": 28800,
    "verify_gravity_600cell_dust_implicit_jacobian.py": 2400,
    "verify_gravity_600cell_dust_internal_curvature_response.py": 28800,
    "verify_gravity_600cell_dust_lapse_schur.py": 2400,
    "verify_gravity_600cell_dust_later_slab_tangent.py": 7200,
    "verify_gravity_600cell_dust_mass_response.py": 18000,
    "verify_gravity_600cell_dust_mass_response_adversarial.py": 18000,
    "verify_gravity_600cell_dust_negative_fiber_transport.py": 600,
    "verify_gravity_600cell_dust_negative_intersection_roundoff_resolution.py": 18000,
    "verify_gravity_600cell_dust_negative_shape_dynamics.py": 3600,
    "verify_gravity_600cell_dust_negative_shape_kinetic_metric.py": 3600,
    "verify_gravity_600cell_dust_negative_shape_root_count.py": 3600,
    "verify_gravity_600cell_dust_negative_transported_intersection.py": 18000,
    "verify_gravity_600cell_dust_negative_transported_intersection_adversarial.py": 18000,
    "verify_gravity_600cell_dust_nonlinear_boundary_covariance.py": 14400,
    "verify_gravity_600cell_dust_nonlinear_boundary_covariance_seeds.py": 14400,
    "verify_gravity_600cell_dust_nonlinear_defect.py": 3000,
    "verify_gravity_600cell_dust_nonlinear_relative.py": 3000,
    "verify_gravity_600cell_dust_pseudolongitudinal_shifted.py": 3600,
    "verify_gravity_600cell_dust_pseudolongitudinal_shifted_adversarial.py": 7200,
    "verify_gravity_600cell_dust_pseudolongitudinal_shifted_rank_correction.py": 300,
    "verify_gravity_600cell_dust_regular_lapse_identity.py": 3600,
    "verify_gravity_600cell_dust_rigidity_york.py": 3600,
    "verify_gravity_600cell_dust_second_homothetic_tick.py": 3600,
    "verify_gravity_600cell_dust_second_tick_homotopy.py": 14400,
    "verify_gravity_600cell_dust_second_tick_local_correction.py": 3600,
    "verify_gravity_600cell_dust_second_tick_stationary_target.py": 300,
    "verify_gravity_600cell_dust_shape_stiffness.py": 3600,
    "verify_gravity_600cell_dust_shifted_centered.py": 3600,
    "verify_gravity_600cell_dust_shifted_conformal_shape.py": 3600,
    "verify_gravity_600cell_dust_shifted_direct_precision.py": 7200,
    "verify_gravity_600cell_dust_shifted_jacobi.py": 3600,
    "verify_gravity_600cell_dust_shifted_negative_persistence.py": 300,
    "verify_gravity_600cell_dust_shifted_precision_audit.py": 600,
    "verify_gravity_600cell_dust_shifted_shape_stiffness.py": 3600,
    "verify_gravity_600cell_dust_stagnation.py": 3000,
    "verify_gravity_600cell_dust_stationary_base.py": 3000,
    "verify_gravity_600cell_dust_stationary_momentum_envelope.py": 14400,
    "verify_gravity_600cell_dust_stationary_root_enumeration.py": 14400,
    "verify_gravity_600cell_dust_third_tick_local_correction.py": 3600,
    "verify_gravity_600cell_dust_third_tick_stationary_roots.py": 14400,
    "verify_gravity_600cell_dust_third_tick_stationary_target.py": 300,
    "verify_gravity_600cell_dust_three_slice_jacobi.py": 3600,
    "verify_gravity_600cell_dust_two_slab_gluing.py": 28800,
    "verify_gravity_600cell_dust_two_step_full_tangent.py": 7200,
    "verify_gravity_600cell_dust_weak_lapse_recurrence.py": 14400,
    "verify_gravity_600cell_dust_weak_scale_path.py": 3000,
    "verify_gravity_600cell_finite_height_asymptotic_map.py": 3600,
    "verify_gravity_600cell_finite_height_asymptotic_map_adversarial.py": 3600,
    "verify_gravity_600cell_finite_height_census.py": 3600,
    "verify_gravity_600cell_finite_height_classification.py": 3600,
    "verify_gravity_600cell_finite_height_classification_adversarial.py": 3600,
    "verify_gravity_600cell_finite_height_composition.py": 3600,
    "verify_gravity_600cell_finite_height_composition_adversarial.py": 3600,
    "verify_gravity_600cell_finite_height_fourth_slab.py": 3600,
    "verify_gravity_600cell_finite_height_fourth_slab_adversarial.py": 3600,
    "verify_gravity_600cell_finite_height_invariant_region.py": 3600,
    "verify_gravity_600cell_finite_height_invariant_region_adversarial.py": 3600,
    "verify_gravity_600cell_finite_height_selector_audit.py": 300,
    "verify_gravity_600cell_finite_height_selector_audit_adversarial.py": 300,
    "verify_gravity_600cell_finite_height_third_slab.py": 3600,
    "verify_gravity_600cell_finite_height_third_slab_adversarial.py": 3600,
    "verify_gravity_600cell_full_equation_carrier_no_go.py": 300,
    "verify_gravity_600cell_full_scale_strut_canonical_intersection.py": 14400,
    "verify_gravity_600cell_full_scale_strut_canonical_precision.py": 28800,
    "verify_gravity_600cell_full_scale_strut_canonical_precision_adversarial.py": 28800,
    "verify_gravity_600cell_full_scale_strut_carrier.py": 14400,
    "verify_gravity_600cell_full_scale_strut_homogeneous_resolution.py": 1800,
    "verify_gravity_600cell_full_scale_strut_homogeneous_resolution_adversarial.py": 14400,
    "verify_gravity_600cell_full_scale_strut_precision.py": 14400,
    "verify_gravity_600cell_full_scale_strut_symbolic_adversarial.py": 3600,
    "verify_gravity_600cell_full_scale_strut_symbolic_gap_resolution.py": 3600,
    "verify_gravity_600cell_generic_velocity_composition.py": 3600,
    "verify_gravity_600cell_generic_velocity_composition_adversarial.py": 3600,
    "verify_gravity_600cell_generic_velocity_cubic.py": 3600,
    "verify_gravity_600cell_generic_velocity_cubic_adversarial.py": 3600,
    "verify_gravity_600cell_generic_velocity_next_order.py": 3600,
    "verify_gravity_600cell_generic_velocity_next_order_adversarial.py": 3600,
    "verify_gravity_600cell_global_flex_holonomy.py": 300,
    "verify_gravity_600cell_global_flex_holonomy_adversarial.py": 1800,
    "verify_gravity_600cell_global_variable_face_closure.py": 3600,
    "verify_gravity_600cell_homogeneous_pole_transversality.py": 300,
    "verify_gravity_600cell_homothetic_frustum_action.py": 3600,
    "verify_gravity_600cell_local_data_lift.py": 3600,
    "verify_gravity_600cell_orbit_action_incidence.py": 7200,
    "verify_gravity_600cell_projected_rank_edgewise_acceleration_adversarial.py": 3600,
    "verify_gravity_600cell_projected_rank_edgewise_acceleration_blind.py": 3600,
    "verify_gravity_600cell_projected_rank_edgewise_acceleration_comparison.py": 3600,
    "verify_gravity_600cell_projected_rank_edgewise_local_dust.py": 3600,
    "verify_gravity_600cell_projected_rank_edgewise_local_dust_adversarial.py": 3600,
    "verify_gravity_600cell_projected_refinement_acceleration_blind.py": 3600,
    "verify_gravity_600cell_projected_refinement_acceleration_comparison.py": 3600,
    "verify_gravity_600cell_published_dust_control.py": 1800,
    "verify_gravity_600cell_rational_data_lift.py": 3600,
    "verify_gravity_600cell_refined_h4_nested_reduction.py": 28800,
    "verify_gravity_600cell_refined_nonhomogeneous_coxeter_blocks.py": 14400,
    "verify_gravity_600cell_refined_nonhomogeneous_coxeter_blocks_adversarial.py": 14400,
    "verify_gravity_600cell_refined_nonhomogeneous_coxeter_census.py": 43200,
    "verify_gravity_600cell_refined_nonhomogeneous_coxeter_census_adversarial.py": 43200,
    "verify_gravity_600cell_refined_nonhomogeneous_internal_hessian.py": 28800,
    "verify_gravity_600cell_refined_nonhomogeneous_internal_hessian_diagnostic.py": 7200,
    "verify_gravity_600cell_relational_step_composition.py": 3600,
    "verify_gravity_600cell_relational_step_composition_adversarial.py": 3600,
    "verify_gravity_600cell_static_gradient_prism_shift_reconciliation.py": 1800,
    "verify_gravity_600cell_static_vertex_gradient.py": 3600,
    "verify_gravity_600cell_static_vertex_gradient_adversarial.py": 1800,
    "verify_gravity_600cell_tick_scale_covariance.py": 3600,
    "verify_gravity_600cell_tick_scale_covariance_adversarial.py": 3600,
    "verify_gravity_600cell_tick_scale_covariance_precision.py": 7200,
    "verify_gravity_600cell_tick_scale_covariance_state_correction.py": 7200,
    "verify_gravity_600cell_two_frustum_face_gluing.py": 300,
    "verify_gravity_600cell_two_frustum_face_gluing_adversarial.py": 300,
    "verify_gravity_600cell_variable_face_connection.py": 300,
    "verify_gravity_600cell_variable_face_connection_adversarial.py": 300,
    "verify_gravity_global_boundary_legendre.py": 1800,
    "verify_gravity_global_regge_roots.py": 1800,
}

results: dict[str, str] = {}
total_time = 0.0

for script in scripts:
    print("\n" + "=" * 70)
    print(f"RUNNING: {script}")
    print("=" * 70)
    started = time.time()
    timeout = SCRIPT_TIMEOUTS.get(script, DEFAULT_TIMEOUT)
    try:
        result = subprocess.run(
            [sys.executable, script],
            capture_output=False,
            timeout=timeout,
            check=False,
        )
        elapsed = time.time() - started
        total_time += elapsed
        results[script] = "PASS" if result.returncode == 0 else "FAIL"
        print(f"\n  Completed in {elapsed:.1f}s -- {results[script]}")
    except subprocess.TimeoutExpired:
        results[script] = "TIMEOUT"
        print(f"\n  TIMEOUT after {timeout}s")
    except Exception as error:
        results[script] = f"ERROR: {error}"
        print(f"\n  ERROR: {error}")

print("\n" + "=" * 70)
print("SUMMARY")
print("=" * 70)
for script, status in results.items():
    print(f"  {script:72s} {status}")
print(f"\nTotal time: {total_time:.1f}s")

n_pass = sum(status == "PASS" for status in results.values())
print(f"Result: {n_pass}/{len(scripts)} scripts completed successfully.")
if n_pass != len(scripts):
    sys.exit(1)
