#!/usr/bin/env python3
"""Exact certificates for the central-parity segregation theorem."""

from itertools import product
from collections import Counter
import sympy as sp


run = passed = 0


def check(label, condition, detail=""):
    global run, passed
    run += 1
    passed += int(bool(condition))
    print(f"  [{'PASS' if condition else 'FAIL'}] {label}")
    if detail:
        print(f"         {detail}")


print("=" * 78)
print("CENTRAL-PARITY SEGREGATION AND ODD-SUBGROUP ESCAPES")
print("=" * 78)

# Work in the exact concrete model 2I = SL(2,5).  Matrices are flattened
# row-wise tuples and all arithmetic is modulo 5.
def det(a):
    return (a[0] * a[3] - a[1] * a[2]) % 5


def mul(a, b):
    return ((a[0]*b[0] + a[1]*b[2]) % 5,
            (a[0]*b[1] + a[1]*b[3]) % 5,
            (a[2]*b[0] + a[3]*b[2]) % 5,
            (a[2]*b[1] + a[3]*b[3]) % 5)


I = (1, 0, 0, 1)
Z = (4, 0, 0, 4)
G = tuple(a for a in product(range(5), repeat=4) if det(a) == 1)
check("SL(2,5) has order 120", len(G) == 120)
involutions = tuple(a for a in G if a != I and mul(a, a) == I)
check("the unique involution is -I", involutions == (Z,), f"involutions={involutions}")


def cyclic(g):
    out, x = {I}, I
    while True:
        x = mul(x, g)
        if x in out:
            return frozenset(out)
        out.add(x)


cyclic_subgroups = {cyclic(g) for g in G}
orders = Counter(len(H) for H in cyclic_subgroups)
check("there are exactly ten C3 and six C5 subgroups",
      orders[3] == 10 and orders[5] == 6,
      f"cyclic subgroup counts={dict(sorted(orders.items()))}")
check("every subgroup generated by an odd-order element has order 1, 3, or 5",
      set(k for k in orders if k % 2) == {1, 3, 5})

# Exclude a noncyclic order-15 subgroup directly.  Any such subgroup would
# contain a C5.  Its image in A5 would normalize that C5; the exact normalizer
# in SL(2,5) has order 20, hence its image normalizer has order 10.
C5 = next(H for H in cyclic_subgroups if len(H) == 5)
def inv(g):
    return (g[3] % 5, (-g[1]) % 5, (-g[2]) % 5, g[0] % 5)


normalizer = tuple(g for g in G
                   if frozenset(mul(mul(g, h), inv(g)) for h in C5) == C5)
check("the C5 normalizer has order 20 in 2I and 10 in A5",
      len(normalizer) == 20 and Z in normalizer)
check("A5 has no order-15 subgroup", 15 > len(normalizer) // 2,
      "an order-15 subgroup would normalize its unique Sylow C5")

# W is the multiplicity-one sum of all nine irreps.  Derive its cyclic
# restrictions from the exact 2I character table in repository class order
# (1A,2A,4A,6A,3A,10A,5A,5B,10B).
sqrt5 = sp.sqrt(5)
phi, phip = (1 + sqrt5)/2, (1 - sqrt5)/2
x = (2, -2, 0, 1, -1, phi, -phi, phi-1, phip)
xp = (2, -2, 0, 1, -1, phip, phi-1, -phi, phi)


def symmetric_powers(t):
    out = [(1,)*9, t]
    for _ in range(2, 6):
        out.append(tuple(sp.expand(t[k]*out[-1][k] - out[-2][k])
                         for k in range(9)))
    return out


sx, sxp = symmetric_powers(x), symmetric_powers(xp)
standard = (sx[0], x, xp, sx[2], sxp[2],
            tuple(sp.expand(x[k]*xp[k]) for k in range(9)),
            sx[3], sx[4], sx[5])
chars = tuple(standard[i] for i in (0, 1, 3, 6, 7, 8, 5, 2, 4))
dims = (1, 2, 3, 4, 5, 6, 4, 2, 3)
parity = (0, 1, 0, 1, 0, 1, 0, 1, 0)
even_dim = sum(d for d, p in zip(dims, parity) if p == 0)
odd_dim = sum(d for d, p in zip(dims, parity) if p == 1)


def restricted_weights(n, classes, sector):
    values = [sum(chars[i][c] for i in range(9) if parity[i] == sector)
              for c in classes]
    zeta = sp.exp(2*sp.pi*sp.I/n)
    ans = []
    for j in range(n):
        value = sp.simplify(sp.expand_complex(
            sum(values[k]*zeta**(-j*k) for k in range(n))/n))
        ans.append(int(value))
    return tuple(ans)


c3_even = restricted_weights(3, (0, 4, 4), 0)
c3_odd = restricted_weights(3, (0, 4, 4), 1)
c5_even = restricted_weights(5, (0, 6, 7, 7, 6), 0)
c5_odd = restricted_weights(5, (0, 6, 7, 7, 6), 1)


def odd_operator_dim(a, b):
    # Hom_H(W+,W-) plus Hom_H(W-,W+), complex dimension.
    return 2 * sum(x*y for x, y in zip(a, b))


check("W has central-parity dimensions 16+14", even_dim + odd_dim == 30)
check("exact C3 weights are (6,5,5) and (4,5,5)",
      c3_even == (6, 5, 5) and c3_odd == (4, 5, 5))
check("exact C5 weights are (4,3,3,3,3) and (2,3,3,3,3)",
      c5_even == (4, 3, 3, 3, 3) and c5_odd == (2, 3, 3, 3, 3))
check("dim_C OddEnd_C5(W)=88",
      odd_operator_dim(c5_even, c5_odd) == 88)
check("dim_C OddEnd_C3(W)=148",
      odd_operator_dim(c3_even, c3_odd) == 148)
check("dim_C OddEnd_C1(W)=448",
      2 * even_dim * odd_dim == 448)

# Canonical seed restrictions for labels (1,1bar,2,3,3bar).  Weight vectors
# use characters of C_n.  A cell is r_i tensor conjugate(r_j).
def convolution(a, b):
    n = len(a)
    return tuple(sum(a[k] * b[(k-j) % n] for k in range(n))
                 for j in range(n))


seed_restrictions = {
    3: ((1, 0, 0), (1, 0, 0), (0, 1, 1),
        (1, 1, 1), (1, 1, 1)),
    5: ((1, 0, 0, 0, 0), (1, 0, 0, 0, 0),
        (0, 0, 1, 1, 0), (1, 0, 1, 1, 0),
        (1, 0, 1, 1, 0)),
}


def solution_count(n, target):
    cells = tuple(convolution(a, b) for a in seed_restrictions[n]
                  for b in seed_restrictions[n])
    memo = {}

    def visit(pos, remaining):
        key = (pos, remaining)
        if key in memo:
            return memo[key]
        if pos == len(cells):
            return int(not any(remaining))
        v = cells[pos]
        maximum = min((remaining[k] // v[k] for k in range(n) if v[k]),
                      default=0)
        answer = 0
        for m in range(maximum + 1):
            answer += visit(pos + 1, tuple(remaining[k] - m*v[k]
                                           for k in range(n)))
        memo[key] = answer
        return answer

    return visit(0, tuple(target))


c5_plus = solution_count(5, c5_even)
c5_minus = solution_count(5, c5_odd)
check("canonical C5 seed bimodule has no grading-wise reblocking",
      c5_plus == c5_minus == 0,
      f"plus solutions={c5_plus}, minus solutions={c5_minus}")

# Explicit C3 witness.  Cell indices are row*5+column:
# H+ = (2,2) + 2(3bar,2), H- = (2,1bar) + 2(3bar,2).
plus_cells = (12, 22, 22)
minus_cells = (11, 22, 22)
cells3 = tuple(convolution(a, b) for a in seed_restrictions[3]
               for b in seed_restrictions[3])


def weight_sum(indices):
    return tuple(sum(cells3[i][k] for i in indices) for k in range(3))


check("explicit C3 Krajewski witness reproduces W+",
      weight_sum(plus_cells) == c3_even)
check("explicit C3 Krajewski witness reproduces W-",
      weight_sum(minus_cells) == c3_odd)
legal_odd = ((12 // 5 == 11 // 5) or (12 % 5 == 11 % 5))
check("the C3 witness has a Krajewski-legal odd block type",
      legal_odd, "(2,2) <-> (2,1bar) shares its left H label")
common_weights = tuple(min(cells3[12][k], cells3[11][k]) for k in range(3))
check("the legal C3 cell pair admits a nonzero C3 intertwiner",
      sum(common_weights) > 0, f"common character multiplicities={common_weights}")
check("the C3 witness contains scalar, H, and M3 seed labels",
      {1, 2, 4}.issubset({i for c in plus_cells + minus_cells
                          for i in divmod(c, 5)}))

print("\n" + "-" * 78)
print(f"TOTAL: {passed}/{run} tests PASSED")
print("DERIVED: central parity forbids every 2I-equivariant odd operator.")
print("DERIVED: maximal odd residual groups are C3 and C5.")
print("DERIVED: C3 passes the combinatorial Krajewski block test; C5 does not.")
raise SystemExit(0 if passed == run else 1)
