#!/usr/bin/env python3
"""Symmetry no-go for incidence-only multi-substep metric dynamics.

Protocol commit 51926af froze the full algebra generated by signed incidence
and form-degree projectors.  No phenomenological target is used.
"""

from collections import Counter
from itertools import combinations, permutations
from math import factorial
import json
from pathlib import Path

import sympy as sy


OUTPUT = Path(__file__).with_name("incidence_polynomial_metric_nogo.json")
tests = passed = 0


def check(label, condition, detail=""):
    global tests, passed
    tests += 1
    condition = bool(condition)
    passed += int(condition)
    print(f"  [{'PASS' if condition else 'FAIL'}] {label}")
    if detail:
        print(f"         {detail}")


def permutation_sign(permutation):
    inversions = sum(
        permutation[left] > permutation[right]
        for left in range(len(permutation))
        for right in range(left+1, len(permutation))
    )
    return -1 if inversions % 2 else 1


print("="*78)
print("INCIDENCE-ONLY SUBSTEPS VERSUS ANISOTROPIC WHITNEY METRIC")
print("="*78)

# -------------------------------------------------------------------------
# Exact oriented simplex carrier and the full signed S4 action.
# -------------------------------------------------------------------------
simplices = [list(combinations(range(4), degree+1))
             for degree in range(4)]
dims = tuple(map(len, simplices))
offsets = [0]
for size in dims:
    offsets.append(offsets[-1]+size)
indices = [{simplex: index for index, simplex in enumerate(layer)}
           for layer in simplices]

differentials = []
for degree in range(3):
    matrix = sy.zeros(dims[degree+1], dims[degree])
    for row, simplex in enumerate(simplices[degree+1]):
        for omitted in range(degree+2):
            face = simplex[:omitted]+simplex[omitted+1:]
            matrix[row, indices[degree][face]] = (-1)**omitted
    differentials.append(matrix)

D = sy.zeros(sum(dims))
for degree in range(3):
    D[offsets[degree+1]:offsets[degree+2],
      offsets[degree]:offsets[degree+1]] = differentials[degree]
    D[offsets[degree]:offsets[degree+1],
      offsets[degree+1]:offsets[degree+2]] = differentials[degree].T

degree_projectors = []
for degree in range(4):
    projector = sy.zeros(sum(dims))
    projector[offsets[degree]:offsets[degree+1],
              offsets[degree]:offsets[degree+1]] = sy.eye(dims[degree])
    degree_projectors.append(projector)


def cochain_action(vertex_permutation, degree):
    matrix = sy.zeros(dims[degree])
    for source, simplex in enumerate(simplices[degree]):
        image = [vertex_permutation[vertex] for vertex in simplex]
        sorting = tuple(sorted(range(len(image)), key=image.__getitem__))
        target_simplex = tuple(sorted(image))
        target = indices[degree][target_simplex]
        matrix[target, source] = permutation_sign(sorting)
    return matrix


vertex_permutations = tuple(permutations(range(4)))
layer_actions = [
    tuple(cochain_action(permutation, degree) for degree in range(4))
    for permutation in vertex_permutations
]
full_actions = [sy.diag(*actions) for actions in layer_actions]
check("all 24 vertex permutations act by exact signed cochain matrices",
      len(full_actions) == 24
      and all(action.T*action == sy.eye(sum(dims))
              for action in full_actions))
check("every signed coboundary is S4-equivariant",
      all(
          actions[degree+1]*differentials[degree]
          == differentials[degree]*actions[degree]
          for actions in layer_actions
          for degree in range(3)
      ))
check("D and all four degree projectors commute with the complete S4 action",
      all(action*D == D*action for action in full_actions)
      and all(action*projector == projector*action
              for action in full_actions
              for projector in degree_projectors),
      "therefore every word in <D,P0,P1,P2,P3> is S4-equivariant")

# -------------------------------------------------------------------------
# Exact three-step path census between nonincident adjacent-degree pairs.
# -------------------------------------------------------------------------
D_cubed = D**3
path_records = []
unsigned_multiset = Counter()
signed_multiset = Counter()
for degree in (0, 1):
    for low, low_simplex in enumerate(simplices[degree]):
        for high, high_simplex in enumerate(simplices[degree+1]):
            low_global = offsets[degree]+low
            high_global = offsets[degree+1]+high
            if D[low_global, high_global] != 0:
                continue
            path_count = 0
            signed_sum = 0
            for middle_one in range(sum(dims)):
                if D[low_global, middle_one] == 0:
                    continue
                for middle_two in range(sum(dims)):
                    if (D[middle_one, middle_two] != 0
                            and D[middle_two, high_global] != 0):
                        path_count += 1
                        signed_sum += (
                            D[low_global, middle_one]
                            * D[middle_one, middle_two]
                            * D[middle_two, high_global]
                        )
            unsigned_multiset[path_count] += 1
            signed_multiset[int(signed_sum)] += 1
            path_records.append({
                "degree": degree,
                "low_simplex": list(low_simplex),
                "high_simplex": list(high_simplex),
                "unsigned_length_three_paths": path_count,
                "signed_path_sum": int(signed_sum),
                "D_cubed_entry": int(D_cubed[low_global, high_global]),
            })

check("the exact length-three path census is 12 pairs with four paths and 12 with six",
      unsigned_multiset == Counter({4: 12, 6: 12}),
      str(dict(unsigned_multiset)))
check("all signed length-three path sums cancel exactly for all 24 pairs",
      signed_multiset == Counter({0: 24})
      and all(record["D_cubed_entry"] == 0 for record in path_records),
      "(D^3)_xy=0 on every candidate off-incidence entry")

# -------------------------------------------------------------------------
# Exact Whitney metric on the fixed barycentric flag geometry.
# -------------------------------------------------------------------------
coordinate_bases = [list(combinations(range(3), degree))
                    for degree in range(4)]


def wedge_components(covectors, degree):
    if degree == 0:
        return sy.Matrix((1,))
    return sy.Matrix([
        sy.det(sy.Matrix([
            [covector[index] for index in basis]
            for covector in covectors
        ]))
        for basis in coordinate_bases[degree]
    ])


def local_whitney_mass(points, degree):
    affine = sy.Matrix.hstack(
        points[1]-points[0], points[2]-points[0], points[3]-points[0]
    )
    inverse = affine.inv()
    gradients = [-sum(
        (sy.Matrix(inverse.row(row)).T for row in range(3)),
        sy.zeros(3, 1),
    )]
    gradients.extend(sy.Matrix(inverse.row(row)).T for row in range(3))
    volume = abs(affine.det())/6
    barycentric_second_moment = volume*(sy.ones(4, 4)+sy.eye(4))/20
    forms = list(combinations(range(4), degree+1))
    coefficients_all = []
    for form in forms:
        coefficients = sy.zeros(len(coordinate_bases[degree]), 4)
        if degree == 0:
            coefficients[0, form[0]] = 1
        else:
            for omitted in range(degree+1):
                covectors = [
                    gradients[form[index]]
                    for index in range(degree+1)
                    if index != omitted
                ]
                coefficients[:, form[omitted]] += (
                    factorial(degree)*(-1)**omitted
                    * wedge_components(covectors, degree)
                )
        coefficients_all.append(coefficients)

    mass = sy.zeros(len(forms), len(forms))
    for row, left in enumerate(coefficients_all):
        for column, right in enumerate(coefficients_all):
            mass[row, column] = sy.simplify(sum(
                (left[basis, :]*barycentric_second_moment
                 * right[basis, :].T)[0]
                for basis in range(len(coordinate_bases[degree]))
            ))
    return mass


regular_vertices = tuple(map(sy.Matrix, (
    (1, 1, 1),
    (1, -1, -1),
    (-1, 1, -1),
    (-1, -1, 1),
)))
flag_child = (
    regular_vertices[0],
    (regular_vertices[0]+regular_vertices[1])/2,
    (regular_vertices[0]+regular_vertices[1]+regular_vertices[2])/3,
    sum(regular_vertices, sy.zeros(3, 1))/4,
)


def whitney_strong_operator(points):
    masses = [local_whitney_mass(points, degree) for degree in range(4)]
    operator = sy.zeros(sum(dims))
    for degree in range(3):
        delta = sy.simplify(
            masses[degree].inv()
            * differentials[degree].T
            * masses[degree+1]
        )
        operator[offsets[degree+1]:offsets[degree+2],
                 offsets[degree]:offsets[degree+1]] = differentials[degree]
        operator[offsets[degree]:offsets[degree+1],
                 offsets[degree+1]:offsets[degree+2]] = delta
    return operator, masses


regular_operator, regular_masses = whitney_strong_operator(regular_vertices)
child_operator, child_masses = whitney_strong_operator(flag_child)
regular_stabilizer = tuple(
    number for number, action in enumerate(full_actions)
    if action*regular_operator == regular_operator*action
)
child_stabilizer = tuple(
    number for number, action in enumerate(full_actions)
    if action*child_operator == child_operator*action
)
check("the regular Whitney control retains the complete S4 stabilizer",
      len(regular_stabilizer) == 24)
check("the barycentric flag Whitney operator has a trivial S4 stabilizer",
      len(child_stabilizer) == 1,
      f"stabilizer order={len(child_stabilizer)}")

# Any element of the generator algebra commutes with all 24 actions.  The
# child operator commutes only with the identity, so equality is impossible
# regardless of word length or coefficients.
incidence_only_impossible = len(child_stabilizer) < 24
check("no incidence-and-degree word can equal the anisotropic Whitney operator",
      incidence_only_impossible,
      "the obstruction covers every polynomial degree, not only D^3")

payload = {
    "protocol_commit": "51926af",
    "phenomenological_target_used": False,
    "generator_algebra": {
        "generators": ["D", "P0", "P1", "P2", "P3"],
        "S4_equivariant": True,
        "S4_order": 24,
    },
    "three_step_paths": {
        "nonincident_pair_count": len(path_records),
        "unsigned_path_count_multiset": {
            str(key): value for key, value in sorted(unsigned_multiset.items())
        },
        "signed_path_sum_multiset": {
            str(key): value for key, value in sorted(signed_multiset.items())
        },
        "records": path_records,
    },
    "whitney_symmetry": {
        "regular_tetrahedron_stabilizer_order": len(regular_stabilizer),
        "barycentric_flag_child_stabilizer_order": len(child_stabilizer),
    },
    "verdict": (
        "DERIVED NO-GO FOR INCIDENCE-ONLY SUBSTEPS: D^3 cancels on all "
        "candidate off-incidence pairs, and the entire algebra generated by "
        "D and form-degree projectors is S4-equivariant while the fixed "
        "Whitney flag operator has trivial S4 stabilizer."
    ),
    "open": (
        "A geometry-aware local factorization using metric-derived unequal "
        "path weights, enlarged states or nonorthogonal encoding."
    ),
}
OUTPUT.write_text(json.dumps(payload, indent=2, sort_keys=True)+"\n")
check("the structured target-blind symmetry certificate was written",
      OUTPUT.exists())

print("\n"+"-"*78)
print(f"RESULT: {passed}/{tests} checks passed")
print("VERDICT=DERIVED_NO_GO_FOR_INCIDENCE_ONLY_SUBSTEPS")
print("D_CUBED_OFF_INCIDENCE=0_FOR_ALL_24_PAIRS")
print(f"WHITNEY_FLAG_S4_STABILIZER={len(child_stabilizer)}")
print("OPEN: geometry-aware unequal path weights and a unitary factorization.")
raise SystemExit(0 if passed == tests else 1)
